# Generated by Django 3.1 on 2020-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='amount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
